import type { NodeDefinition } from "./types";

const anySchema = { type: "any" as const };

export const nodeDefinitions: NodeDefinition[] = [
  {
    type: "manual.trigger",
    name: "Manual Trigger",
    description: "Start this workflow from the UI, API, or command palette.",
    icon: "Play",
    category: "trigger",
    color: "var(--accent)",
    docs: "Use when a person or an API client should kick off a run with optional JSON input.",
    isTrigger: true,
    inputs: 0,
    outputs: [{ id: "out", label: "Input" }],
    configFields: [
      {
        key: "sampleInput",
        label: "Sample input",
        type: "json",
        description: "Used when testing from the editor.",
        default: { source: "manual" },
      },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", description: "The payload provided at run time." },
  },
  {
    type: "schedule.trigger",
    name: "Schedule Trigger",
    description: "Run on a cron schedule.",
    icon: "Clock",
    category: "trigger",
    color: "var(--accent)",
    docs: "Supports standard 5-field cron expressions. The worker evaluates due schedules independently of HTTP.",
    isTrigger: true,
    inputs: 0,
    outputs: [{ id: "out", label: "Tick" }],
    configFields: [
      { key: "cron", label: "Cron", type: "cron", required: true, placeholder: "0 9 * * 1-5", default: "0 9 * * 1-5" },
      { key: "timezone", label: "Timezone", type: "string", default: "UTC", advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        scheduledFor: { type: "string" },
        cron: { type: "string" },
      },
    },
  },
  {
    type: "webhook.trigger",
    name: "Webhook Trigger",
    description: "Receive HTTP events from other systems.",
    icon: "Webhook",
    category: "trigger",
    color: "var(--accent)",
    docs: "Each workflow gets a unique URL. Optional HMAC validation lives on the workflow webhook token.",
    isTrigger: true,
    inputs: 0,
    outputs: [{ id: "out", label: "Request" }],
    configFields: [
      { key: "pathHint", label: "Path hint", type: "string", placeholder: "stripe-invoice" },
      { key: "requireSignature", label: "Require signature", type: "boolean", default: false, advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        method: { type: "string" },
        headers: { type: "object" },
        query: { type: "object" },
        body: { type: "any" },
      },
    },
  },
  {
    type: "form.trigger",
    name: "Form Trigger",
    description: "Collect structured input from a form submission.",
    icon: "ClipboardList",
    category: "trigger",
    color: "var(--accent)",
    docs: "Define fields that become the trigger payload.",
    isTrigger: true,
    inputs: 0,
    outputs: [{ id: "out", label: "Submission" }],
    configFields: [
      {
        key: "fields",
        label: "Fields",
        type: "json",
        default: [
          { key: "name", label: "Name", type: "string", required: true },
          { key: "email", label: "Email", type: "string", required: true },
        ],
      },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
  {
    type: "ai.prompt",
    name: "AI Prompt",
    description: "Call a language model with a prompt and variables.",
    icon: "Sparkles",
    category: "ai",
    color: "#7c6af7",
    docs: "Uses the configured AI provider. SpaceXAI (Grok) is the default.",
    inputs: 1,
    outputs: [{ id: "out", label: "Completion" }],
    configFields: [
      { key: "provider", label: "Provider", type: "select", options: [
        { value: "xai", label: "SpaceXAI" },
        { value: "openai", label: "OpenAI" },
        { value: "anthropic", label: "Anthropic" },
        { value: "gemini", label: "Gemini" },
        { value: "mock", label: "Mock" },
      ], default: "xai", advanced: true },
      { key: "model", label: "Model", type: "model", default: "grok-4.6", advanced: true },
      { key: "system", label: "System", type: "text", placeholder: "You are a precise operations assistant." },
      { key: "prompt", label: "Prompt", type: "expression", required: true, placeholder: "Write a reply for {{trigger.body.name}}" },
      { key: "temperature", label: "Temperature", type: "number", default: 0.2, advanced: true },
      { key: "json", label: "JSON mode", type: "boolean", default: false, advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        text: { type: "string" },
        json: { type: "any" },
        model: { type: "string" },
        usage: { type: "object" },
      },
    },
  },
  {
    type: "ai.classifier",
    name: "AI Classifier",
    description: "Classify input into a fixed set of labels.",
    icon: "Tags",
    category: "ai",
    color: "#7c6af7",
    docs: "Returns a label, confidence, and reasons. Downstream Switch nodes can branch on the label.",
    inputs: 1,
    outputs: [{ id: "out", label: "Classification" }],
    configFields: [
      { key: "provider", label: "Provider", type: "select", default: "xai", options: [
        { value: "xai", label: "SpaceXAI" },
        { value: "mock", label: "Mock" },
      ], advanced: true },
      { key: "model", label: "Model", type: "model", default: "grok-4.6", advanced: true },
      {
        key: "labels",
        label: "Labels",
        type: "json",
        required: true,
        default: ["qualified", "nurture", "disqualified"],
      },
      { key: "input", label: "Input", type: "expression", required: true, placeholder: "{{trigger.body}}" },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        label: { type: "string" },
        confidence: { type: "number" },
        reasons: { type: "array", items: { type: "string" } },
      },
    },
  },
  {
    type: "ai.extractor",
    name: "AI Extractor",
    description: "Extract structured fields from unstructured text.",
    icon: "ScanText",
    category: "ai",
    color: "#7c6af7",
    docs: "Describe the fields you want. The model returns JSON matching those keys.",
    inputs: 1,
    outputs: [{ id: "out", label: "Fields" }],
    configFields: [
      { key: "provider", label: "Provider", type: "select", default: "xai", options: [
        { value: "xai", label: "SpaceXAI" },
        { value: "mock", label: "Mock" },
      ], advanced: true },
      { key: "model", label: "Model", type: "model", default: "grok-4.6", advanced: true },
      { key: "input", label: "Source", type: "expression", required: true, placeholder: "{{trigger.body}}" },
      {
        key: "schema",
        label: "Fields",
        type: "json",
        default: { name: "string", email: "string", company: "string" },
      },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
  {
    type: "ai.summarizer",
    name: "AI Summarizer",
    description: "Compress long content into a brief, usable summary.",
    icon: "FileText",
    category: "ai",
    color: "#7c6af7",
    docs: "Good for meetings, tickets, and documents.",
    inputs: 1,
    outputs: [{ id: "out", label: "Summary" }],
    configFields: [
      { key: "provider", label: "Provider", type: "select", default: "xai", options: [
        { value: "xai", label: "SpaceXAI" },
        { value: "mock", label: "Mock" },
      ], advanced: true },
      { key: "model", label: "Model", type: "model", default: "grok-4.6", advanced: true },
      { key: "input", label: "Source", type: "expression", required: true },
      { key: "style", label: "Style", type: "select", default: "bullets", options: [
        { value: "bullets", label: "Bullets" },
        { value: "paragraph", label: "Paragraph" },
        { value: "executive", label: "Executive" },
      ] },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        summary: { type: "string" },
        bullets: { type: "array", items: { type: "string" } },
      },
    },
  },
  {
    type: "ai.agent",
    name: "AI Agent",
    description: "A tool-using agent that can reason across multiple steps.",
    icon: "Bot",
    category: "ai",
    color: "#7c6af7",
    docs: "v1 runs a single reasoned pass with optional HTTP tool use described in the goal. Full tool loops land as additional adapters.",
    inputs: 1,
    outputs: [{ id: "out", label: "Result" }],
    configFields: [
      { key: "provider", label: "Provider", type: "select", default: "xai", options: [
        { value: "xai", label: "SpaceXAI" },
        { value: "mock", label: "Mock" },
      ], advanced: true },
      { key: "model", label: "Model", type: "model", default: "grok-4.6", advanced: true },
      { key: "goal", label: "Goal", type: "expression", required: true },
      { key: "context", label: "Context", type: "expression" },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        result: { type: "string" },
        actions: { type: "array" },
      },
    },
  },
  {
    type: "logic.condition",
    name: "Condition",
    description: "Branch true or false based on an expression.",
    icon: "GitBranch",
    category: "logic",
    color: "#3d9a6a",
    docs: "Expression must evaluate to a boolean. Connect the true/false handles independently.",
    inputs: 1,
    outputs: [
      { id: "true", label: "True" },
      { id: "false", label: "False" },
    ],
    configFields: [
      { key: "expression", label: "Expression", type: "expression", required: true, placeholder: "score >= 80" },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: { result: { type: "boolean" }, input: { type: "any" } },
    },
  },
  {
    type: "logic.switch",
    name: "Switch",
    description: "Route on a discrete value.",
    icon: "Split",
    category: "logic",
    color: "#3d9a6a",
    docs: "Cases are compared with ===. Unmatched values follow the default handle.",
    inputs: 1,
    outputs: [
      { id: "default", label: "Default" },
    ],
    configFields: [
      { key: "value", label: "Value", type: "expression", required: true, placeholder: "{{nodes.classify.label}}" },
      {
        key: "cases",
        label: "Cases",
        type: "json",
        default: ["qualified", "nurture", "disqualified"],
      },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", properties: { value: { type: "any" }, matched: { type: "string" } } },
  },
  {
    type: "logic.loop",
    name: "Loop",
    description: "Iterate over a list and fan items downstream.",
    icon: "Repeat",
    category: "logic",
    color: "#3d9a6a",
    docs: "Each item is passed as `item` with `index`. Downstream nodes run once per item in sequence.",
    inputs: 1,
    outputs: [{ id: "out", label: "Item" }],
    configFields: [
      { key: "items", label: "Items", type: "expression", required: true, placeholder: "{{nodes.parse.items}}" },
      { key: "maxItems", label: "Max items", type: "number", default: 50, advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", properties: { item: { type: "any" }, index: { type: "number" } } },
  },
  {
    type: "logic.delay",
    name: "Delay",
    description: "Pause the workflow for a duration.",
    icon: "Timer",
    category: "logic",
    color: "#3d9a6a",
    canPause: true,
    docs: "Persists waiting state. The worker resumes when the delay elapses.",
    inputs: 1,
    outputs: [{ id: "out", label: "Continue" }],
    configFields: [
      { key: "ms", label: "Milliseconds", type: "duration", default: 1000 },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", properties: { resumedAt: { type: "string" } } },
  },
  {
    type: "logic.filter",
    name: "Filter",
    description: "Keep or drop items in a list using an expression.",
    icon: "Filter",
    category: "logic",
    color: "#3d9a6a",
    docs: "The expression is evaluated per item as `item`.",
    inputs: 1,
    outputs: [{ id: "out", label: "Kept" }],
    configFields: [
      { key: "items", label: "Items", type: "expression", required: true },
      { key: "expression", label: "Keep when", type: "expression", required: true, placeholder: "item.score >= 50" },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", properties: { items: { type: "array" }, dropped: { type: "number" } } },
  },
  {
    type: "logic.merge",
    name: "Merge",
    description: "Combine incoming branches into one payload.",
    icon: "Merge",
    category: "logic",
    color: "#3d9a6a",
    docs: "Waits until all inbound edges have produced a value, then merges objects.",
    inputs: 2,
    outputs: [{ id: "out", label: "Merged" }],
    configFields: [
      { key: "strategy", label: "Strategy", type: "select", default: "object", options: [
        { value: "object", label: "Shallow object merge" },
        { value: "array", label: "Collect as array" },
      ] },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "any" },
  },
  {
    type: "data.set",
    name: "Set Variable",
    description: "Write a workflow variable for later steps.",
    icon: "Variable",
    category: "data",
    color: "#6b8fd4",
    docs: "Variables are scoped to the execution.",
    inputs: 1,
    outputs: [{ id: "out", label: "Value" }],
    configFields: [
      { key: "name", label: "Name", type: "string", required: true, placeholder: "priority" },
      { key: "value", label: "Value", type: "expression", required: true },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object", properties: { name: { type: "string" }, value: { type: "any" } } },
  },
  {
    type: "data.transform",
    name: "Transform Data",
    description: "Map a payload into a new shape with expressions.",
    icon: "Wand2",
    category: "data",
    color: "#6b8fd4",
    docs: "Each key in the mapping is evaluated as an expression or template.",
    inputs: 1,
    outputs: [{ id: "out", label: "Mapped" }],
    configFields: [
      {
        key: "mapping",
        label: "Mapping",
        type: "json",
        default: { email: "{{trigger.body.email}}", name: "{{trigger.body.name}}" },
      },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
  {
    type: "data.json",
    name: "JSON Parser",
    description: "Parse JSON text or stringify a value.",
    icon: "Braces",
    category: "data",
    color: "#6b8fd4",
    docs: "Fails loudly on invalid JSON unless onError is continue.",
    inputs: 1,
    outputs: [{ id: "out", label: "Value" }],
    configFields: [
      { key: "mode", label: "Mode", type: "select", default: "parse", options: [
        { value: "parse", label: "Parse" },
        { value: "stringify", label: "Stringify" },
      ] },
      { key: "value", label: "Value", type: "expression", required: true },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "any" },
  },
  {
    type: "data.http",
    name: "HTTP Request",
    description: "Call any HTTP API.",
    icon: "Globe",
    category: "data",
    color: "#6b8fd4",
    docs: "Headers and body support templates. Secrets can be referenced by name.",
    inputs: 1,
    outputs: [{ id: "out", label: "Response" }],
    configFields: [
      { key: "method", label: "Method", type: "select", default: "GET", options: [
        { value: "GET", label: "GET" },
        { value: "POST", label: "POST" },
        { value: "PUT", label: "PUT" },
        { value: "PATCH", label: "PATCH" },
        { value: "DELETE", label: "DELETE" },
      ] },
      { key: "url", label: "URL", type: "expression", required: true, placeholder: "https://api.example.com/v1/resource" },
      { key: "headers", label: "Headers", type: "json", default: { Accept: "application/json" }, advanced: true },
      { key: "body", label: "Body", type: "expression", advanced: true },
      { key: "timeoutMs", label: "Timeout (ms)", type: "number", default: 15000, advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        status: { type: "number" },
        headers: { type: "object" },
        body: { type: "any" },
      },
    },
  },
  {
    type: "human.approval",
    name: "Human Approval",
    description: "Pause until a person approves, rejects, or requests changes.",
    icon: "UserCheck",
    category: "human",
    color: "#d4a017",
    canPause: true,
    docs: "Creates an approval record. The execution waits. Approvals work on mobile.",
    inputs: 1,
    outputs: [
      { id: "approved", label: "Approved" },
      { id: "rejected", label: "Rejected" },
      { id: "changes", label: "Changes requested" },
    ],
    configFields: [
      { key: "title", label: "Title", type: "expression", required: true, placeholder: "Approve outreach to {{nodes.extract.company}}" },
      { key: "summary", label: "Summary", type: "expression" },
      { key: "timeoutMinutes", label: "Timeout (minutes)", type: "number", default: 1440, advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        decision: { type: "string" },
        comment: { type: "string" },
        resolvedBy: { type: "string" },
      },
    },
  },
  {
    type: "human.review",
    name: "Human Review",
    description: "Ask a person to inspect a payload and optionally edit it.",
    icon: "Eye",
    category: "human",
    color: "#d4a017",
    canPause: true,
    docs: "Similar to approval, but the reviewer can return an edited payload.",
    inputs: 1,
    outputs: [{ id: "out", label: "Reviewed" }],
    configFields: [
      { key: "title", label: "Title", type: "expression", required: true },
      { key: "instructions", label: "Instructions", type: "text" },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
  {
    type: "comm.email",
    name: "Email",
    description: "Queue an outbound email.",
    icon: "Mail",
    category: "communication",
    color: "#d4675c",
    docs: "v1 records the email as an outbound action. Connect an email provider in Integrations to actually send.",
    inputs: 1,
    outputs: [{ id: "out", label: "Sent" }],
    configFields: [
      { key: "to", label: "To", type: "expression", required: true, placeholder: "{{nodes.extract.email}}" },
      { key: "subject", label: "Subject", type: "expression", required: true },
      { key: "body", label: "Body", type: "expression", required: true },
      { key: "from", label: "From", type: "string", advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: {
      type: "object",
      properties: {
        to: { type: "string" },
        subject: { type: "string" },
        status: { type: "string" },
      },
    },
  },
  {
    type: "comm.notification",
    name: "Notification",
    description: "Notify the workspace about something that happened.",
    icon: "Bell",
    category: "communication",
    color: "#d4675c",
    docs: "Creates an in-app notification and an audit event. Slack/Discord adapters can subscribe later.",
    inputs: 1,
    outputs: [{ id: "out", label: "Notified" }],
    configFields: [
      { key: "title", label: "Title", type: "expression", required: true },
      { key: "message", label: "Message", type: "expression", required: true },
      { key: "severity", label: "Severity", type: "select", default: "info", options: [
        { value: "info", label: "Info" },
        { value: "success", label: "Success" },
        { value: "warning", label: "Warning" },
        { value: "error", label: "Error" },
      ] },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
  {
    type: "output.response",
    name: "Return Response",
    description: "Set the workflow output returned to the caller.",
    icon: "CornerDownLeft",
    category: "output",
    color: "#8b8b93",
    docs: "Useful for webhook-triggered workflows that should return JSON.",
    inputs: 1,
    outputs: [{ id: "out", label: "Done" }],
    configFields: [
      { key: "value", label: "Value", type: "expression", required: true },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "any" },
  },
  {
    type: "output.log",
    name: "Log Result",
    description: "Write a structured log entry for this run.",
    icon: "ScrollText",
    category: "output",
    color: "#8b8b93",
    docs: "Logs appear on the step and in the execution inspector.",
    inputs: 1,
    outputs: [{ id: "out", label: "Logged" }],
    configFields: [
      { key: "message", label: "Message", type: "expression", required: true },
      { key: "data", label: "Data", type: "expression", advanced: true },
    ],
    inputSchema: anySchema,
    outputSchema: { type: "object" },
  },
];

export const nodeDefinitionMap = new Map(nodeDefinitions.map((d) => [d.type, d]));

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return nodeDefinitionMap.get(type);
}

export const nodeCategories: Array<{ id: NodeDefinition["category"]; label: string }> = [
  { id: "trigger", label: "Triggers" },
  { id: "ai", label: "AI" },
  { id: "logic", label: "Logic" },
  { id: "data", label: "Data" },
  { id: "human", label: "Human" },
  { id: "communication", label: "Communication" },
  { id: "output", label: "Output" },
];
